### PR TITLE
Update for 8ball command

### PR DESCRIPTION
**Pull request by DevShaded**
**Description:**  Changed/Cleaned the 8ball command script, hope it will look more readable 

**Justification:** 
* Added more answers in the `answers` array, 

* Removed the 8ball! title, added a new description that returns with the 8ball emoji with your discord id and the response from the bot,

* Original message will show up in the footer of the embed

### CODE REVIEW

**Comment by DevShaded** [comment]
This will return

Screenshot from 2021-02-10 21-32-25

**Comment by beCoditive** [comment]
Thanks for your better command but do not make a pull request send us the code of this we will manual merge it. (You could send us the script via email to - contact@becoditive.ml or join in our discord and give us there)

**Comment by beCoditive** [comment]
Thanks bro for the update we got the code now ww will update it in our next update.

**Comment by beCoditive** [comment]
Please Star the Repo if possible as it will be a greate support to us.

**Pull request closed without merging**
